# Generated by Django 3.2 on 2022-01-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=65)),
                ('last_name', models.CharField(max_length=65)),
                ('father_name', models.CharField(max_length=65)),
                ('Gender', models.CharField(max_length=65)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(max_length=25)),
                ('start_station', models.CharField(max_length=65)),
                ('end_station', models.CharField(max_length=65)),
            ],
        ),
    ]
